### ISSUE TITLE
Update horizontal table scrolling

### ISSUE THREAD

**Issue by LaurenEllwood** [BettercareHealth/learn#102]
See [this commit](https://github.com/BettercareHealth/learn/commit/0880fb41fa420e6d883389a2e6d17c82af5f2acb) for reference on the current setup.

I think this may be affecting the display of tables in Epub too. I removed display-block from the [Epub CSS](https://github.com/BettercareHealth/learn/pull/101/commits/6d2597a9c87e01d15c0a133549e4b4510310e5de) to allow them to use the max width but now some tables with more content/columns are not displaying correctly, see this example of a table in Appendix D in Kindle Previewer:
![Kindle](https://user-images.githubusercontent.com/47851980/74315646-8c1bb480-4d80-11ea-8301-cd4d248a0b48.png)

**Comment by arthurattwell** [comment]
@LaurenEllwood #145 improves table scrolling. We still need to look into improving tables in epub. When you can, could you find a couple of example tables we can use for testing, like this one, and note them here? Then we can investigate when there is time.

**Comment by LaurenEllwood** [comment]
Returning to this @arthurattwell after outputting the Maternal Care epub. The two tables in the Maternal Care appendix are not displaying correctly in Kindle previewer. The far right columns of the table are cutoff with no option to scroll and view that content. See this example of the first table in comparison to its web output.

Epub:
![Capture](https://user-images.githubusercontent.com/47851980/87641505-7acc3f00-c748-11ea-9ae7-2cb4e75d6ce1.JPG)
![Capture1](https://user-images.githubusercontent.com/47851980/87641511-7c960280-c748-11ea-9f7a-7302a43cc52b.JPG)

Web:
![Capture2](https://user-images.githubusercontent.com/47851980/87641416-5a03e980-c748-11ea-8e61-f3960841c269.JPG)

**Comment by arthurattwell** [comment]
Thanks, @LaurenEllwood, I've put this back on my to-do list.

**Comment by arthurattwell** [comment]
@LaurenEllwood I've looked into this, and it's not something CSS can solve. It's a limitation of Kindle. Users on tablets and phones can rotate their device to read in landscape mode, which makes the table readable. On paperwhite (e-ink) devices, users can [switch to landscape mode manually](https://www.liabelle.me/how-to-read-ebooks-in-landscape-mode-on-your-kindle-paperwhite/) if they know how.
