### ISSUE TITLE
Add live tests to FHRH and CHW-MBC

### ISSUE THREAD

**Issue by arthurattwell** [BettercareHealth/learn#37]
_From @arthurattwell on May 19, 2017 15:32_

@nkoeries Have added this issue to keep track of the need to do this.

_Copied from original issue: BettercareHealth/bettercare#100_

**Comment by nkoeries** [comment]
@arthurattwell there are no tests for FHRH.

**Comment by arthurattwell** [comment]
MBC for CHWs does have tests ([e.g.](https://bettercare.co.za/learn/mother-and-baby-care-for-community-health-workers/text/01.html#live-test)). FHRH won't have any.
