### ISSUE TITLE
Learn: changes not displaying and navigation issues

### ISSUE THREAD

**Issue by nkoeries** [BettercareHealth/learn#41]
@arthurattwell @ChristinaRookie 

I ran the mac-command and the bundle exec jekyll serve --config="_config.yml,_configs/_config.live.yml" to test website functionality before moving the updated files to FileZilla. Everything on the staging looked as it should (see screenshots) - Adult HIV hidden, test changed to quiz, etc. 

![screen shot 2018-02-13 at 17 06 08](https://user-images.githubusercontent.com/25847025/36156627-56e99928-10e0-11e8-8c73-15353a403b9d.png)
![screen shot 2018-02-13 at 17 05 52](https://user-images.githubusercontent.com/25847025/36156638-5b4bd990-10e0-11e8-9272-80573917145b.png)
![screen shot 2018-02-13 at 17 05 37](https://user-images.githubusercontent.com/25847025/36156645-5e7b9eb6-10e0-11e8-9008-ab28c6aa25cd.png)

Then I moved the updated files to FileZilla and none of these changes have been copied. In additional there are now navigation issues where the left drop down menu runs below the book covers. Quiz is still chapter and Adult HIV is not hidden. 

![screen shot 2018-02-13 at 17 14 51](https://user-images.githubusercontent.com/25847025/36157052-8b6d8988-10e1-11e8-913a-4153efe92e9a.png)
![screen shot 2018-02-13 at 17 14 59](https://user-images.githubusercontent.com/25847025/36157073-95ae90f4-10e1-11e8-8155-e349a89b7e73.png)

I've rechecked the staging site via .mac-command and jekyll. It 100% on both platforms so I suspect there was an issue with the transfer of files but I cannot trace it. I have attached the list of failed transfers as .xml file that won't attach here. 

The issue runs across different browsers.

**Comment by arthurattwell** [comment]
@nkoeries I see there is pre-processed Javascript on the site (e.g. [here](https://bettercare.co.za/learn/assets/js/bundle.js)) -- i.e. build files that Jekyll hasn't processed. 

Did you definitely upload the contents of `_site`? You may have uploaded `assets` from the repo root, not `_site`?

Just a guess. Have a look. Meanwhile, if you PR your fork's latest changes into the original repo (assuming you want those changes published), I can build and upload if you like.

**Comment by nkoeries** [comment]
@arthurattwell 
Ah, (big) rookie mistake. I moved everything. I have done a clean up but would now need to remove the folders that should not be there. Screenshots of the /learn directory are attached. Please let me know which folders ones to delete as I can't recall what should be there. 

![screen shot 2018-02-13 at 20 13 31](https://user-images.githubusercontent.com/25847025/36166243-878c399a-10fa-11e8-8198-ce16b0a26a74.png)
![screen shot 2018-02-13 at 20 13 22](https://user-images.githubusercontent.com/25847025/36166245-87c248c8-10fa-11e8-8388-f0dc5cfdd3a6.png)
![screen shot 2018-02-13 at 20 13 11](https://user-images.githubusercontent.com/25847025/36166246-87f3f562-10fa-11e8-9b33-588a5c5c50cd.png)

**Comment by arthurattwell** [comment]
You can just remove everything, and replace it with the contents of your
_site folder (after running the live-website command, as you did).

You're welcome to come to our office if you need a fast line.

**Comment by nkoeries** [comment]
Thank you. I will be come to the office between 10 and 10:30.

**Comment by nkoeries** [comment]
Morning. 
The Home Page is not loading correctly and it still has the Adult HIV. The underlying issue may well be the naming of the fork. I just need the last two PR to be merged and then will get to it.

**Comment by arthurattwell** [comment]
@nkoeries Can we close this issue?

**Comment by nkoeries** [comment]
@arthurattwell yes.
