### ISSUE TITLE
Public Health: corrections

### ISSUE THREAD

**Issue by arthurattwell** [BettercareHealth/learn#78]
Requested by Miranda Voss:

- [x] Case study 1 of unit 36. (This based on section 36-4). The question is “Which tools will help in the situation” – The answer should read “The 80/20 rule, the 5-tool, inventory management and visual management”.  Flow management is incorrect and should be deleted
- [ ] At the start of each chapter the heading has been changed from eg 5 to Chapter 5. However the alteration has not been made for chapters 1 and 2
- [ ] On the contents page at the start of the book we have for example Part 1: What are the problems? followed by  “1. Sources of information about communities and information”, and then “2. Measuring health problems”. Could we have Chapter 1 and Chapter 2 rather than just 1 and 2.  Same for all chapters. 
- [x] Furthermore could the units be listed under each chapter? The reader can then see all the contents down to unit level and also see how the book is divided into parts, chapters and units.

**Comment by LouiseSteward** [comment]
Regarding the second point:
> At the start of each chapter the heading has been changed from eg 5 to Chapter 5. However the alteration has not been made for chapters 1 and 2
I can see no evidence that this is the case. The files look correct, as do the relevant pages on the learning platform
<img width="725" alt="Screenshot 2019-07-24 at 10 41 10" src="https://user-images.githubusercontent.com/9106614/61778835-d0a12c00-adff-11e9-9203-f531d79b474f.png">
<img width="390" alt="Screenshot 2019-07-24 at 10 41 25" src="https://user-images.githubusercontent.com/9106614/61778837-d0a12c00-adff-11e9-98b3-b51877cf4e4f.png">
<img width="717" alt="Screenshot 2019-07-24 at 10 41 51" src="https://user-images.githubusercontent.com/9106614/61778839-d0a12c00-adff-11e9-960c-2a52f51e9446.png">
<img width="944" alt="Screenshot 2019-07-24 at 10 42 03" src="https://user-images.githubusercontent.com/9106614/61778841-d139c280-adff-11e9-85f9-e0f47e5a33d0.png">

**Comment by LouiseSteward** [comment]
Resolved in [this](https://github.com/BettercareHealth/learn/pull/80) PR. Closing
